name: Approve

on:
  pull_request:
    branches:
      - master

jobs:
  await:
    name: Await Approval
    runs-on: ubuntu-latest
    steps:
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.8.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: MauritsArissen
      - name: Approved PR
        run: echo Approved!
