name: Approve

on:
  pull_request:
    branches:
      - master

jobs:
  await:
    name: Await Approval
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: MauritsArissen
      - name: Approved PR
        run: echo Approved!