name: Deployment

on:
  push:
    branches: [master]

jobs:
  deploy-bot:
    name: Deploy Bot
    runs-on: ubuntu-latest

    steps:
      # Get the latest source code on the server
      - name: Pull FakkaBot@latest on server
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          PORT: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git reset --hard HEAD
            git pull

      # Download dependencies
      - name: Download dependencies
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          PORT: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            npm install

      # Push database changes
      - name: Push database changes
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          PORT: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            npx prisma db push --schema=./src/database/prd.prisma --accept-data-loss

      # Build production artifacts
      - name: Build production
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          PORT: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            npm run build

      # Flush pm2 logs for fresh logs
      - name: Flush logs
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          PORT: ${{ secrets.PORT }}
          script: |
            pm2 flush fakkabot

      # Restart the bot
      - name: Restart session
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          PORT: ${{ secrets.PORT }}
          script: |
            pm2 restart fakkabot
