name: Version Gate

on:
  pull_request:
    branches:
      - master

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current package version
      id: current_version
      run: |
        echo "::set-output name=version::$(jq -r .version package.json)"
      shell: bash

    - name: Get base branch package version
      id: base_version
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}:base_branch
        git checkout base_branch
        echo "::set-output name=version::$(jq -r .version package.json)"
      shell: bash

    - name: Compare versions
      id: compare_versions
      run: |
        if [ "${{ steps.current_version.outputs.version }}" == "${{ steps.base_version.outputs.version }}" ]; then
          echo "Version in package.json has not been updated"
          exit 1
        else
          echo "Version in package.json has been updated"
        fi
      shell: bash
