name: Version Gate

on:
  pull_request:
    branches:
      - master

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if /src folder or package.json has changes
      id: check_changes
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}:base_branch
        if git diff --name-only base_branch ${{ github.sha }} | grep -q -e '^src/' -e 'package.json'; then
          echo "changed=true" >> $GITHUB_ENV
        else
          echo "changed=false" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Get current package version
      id: current_version
      if: env.changed == 'true'
      run: |
        VERSION=$(jq -r .version package.json)
        echo "version=${VERSION}" >> $GITHUB_ENV
      shell: bash

    - name: Get base branch package version
      id: base_version
      if: env.changed == 'true'
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}:base_branch
        git checkout base_branch
        BASE_VERSION=$(jq -r .version package.json)
        echo "base_version=${BASE_VERSION}" >> $GITHUB_ENV
      shell: bash

    - name: Compare versions
      if: env.changed == 'true'
      run: |
        if [ "${{ env.version }}" == "${{ env.base_version }}" ]; then
          echo "Version in package.json has not been updated"
          exit 1
        else
          echo "Version in package.json has been updated"
        fi
      shell: bash
