name: Version Gate

on:
  pull_request:
    branches:
      - master

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if /src folder or package.json has changes
      id: check_changes
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}:base_branch
        if git diff --name-only base_branch ${{ github.sha }} | grep -q -e '^src/' -e 'package.json'; then
          echo "::set-output name=changed::true"
        else
          echo "::set-output name=changed::false"
        fi
      shell: bash

    - name: Get current package version
      id: current_version
      if: steps.src_changes.outputs.changed == 'true'
      run: |
        echo "::set-output name=version::$(jq -r .version package.json)"
      shell: bash

    - name: Get base branch package version
      id: base_version
      if: steps.src_changes.outputs.changed == 'true'
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}:base_branch
        git checkout base_branch
        echo "::set-output name=version::$(jq -r .version package.json)"
      shell: bash

    - name: Compare versions
      if: steps.src_changes.outputs.changed == 'true'
      run: |
        if [ "${{ steps.current_version.outputs.version }}" == "${{ steps.base_version.outputs.version }}" ]; then
          echo "Version in package.json has not been updated"
          exit 1
        else
          echo "Version in package.json has been updated"
        fi
      shell: bash